"""initial

Revision ID: 9bff1a82a5ee
Revises: 
Create Date: 2026-03-31 17:24:55.354958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bff1a82a5ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('HARMFUL', 'NO_HARM', 'NEAR_MISS', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('CLINICAL_PROCEDURES', 'MEDICATION', 'INFECTION', 'MEDICAL_DEVICE', 'FALLS', 'PRESSURE_ULCERS', 'BLOOD', 'PATIENT_CARE', 'DOCUMENTATION', 'SELF_HARM_BEHAVIOR', 'INFRASTRUCTURE', 'WORK_ORGANIZATION', 'PATIENT_RIGHTS', 'OTHER', name='category'), nullable=False),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'MINIMAL', 'MODERATE', 'SEVERE', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('immediate_actions_taken', sa.Boolean(), nullable=False),
    sa.Column('immediate_actions_desc', sa.Text(), nullable=True),
    sa.Column('preventive_suggestions', sa.Text(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('reporter_anonymous', sa.Boolean(), nullable=False),
    sa.Column('reporter_name', sa.String(length=200), nullable=True),
    sa.Column('reporter_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_TRIAGE', 'REJECTED', 'IN_ANALYSIS', 'ESCALATED_RCA', 'ACTION_PLAN', 'IMPLEMENTING', 'CLOSED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
